{% set name = "async_timeout" %}
{% set pypi_name = "async-timeout" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 7d87a4e8adba8ededb52e579ce6bc8276985888913620c935094c2276fd83382

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3

test:
  imports:
    - async_timeout

about:
  home: https://github.com/aio-libs/async-timeout
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: asyncio-compatible timeout context manager.
  dev_url: https://github.com/aio-libs/async-timeout

extra:
  recipe-maintainers:
    - synapticarbors
